# Encoding: UTF-8
project_name: gontlm-proxy

before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - &build
    id: windows
    main: .
    env:
      # - CGO_ENABLED=0
    goos:
      - windows
      # - linux
      # - darwin
    goarch:
      - amd64
    flags:
      - -mod=vendor
    ldflags:
      - -s -w
      - -X github.com/bdwyertech/gontlm-proxy/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/bdwyertech/gontlm-proxy/cmd.ReleaseVer={{.Version}}
      - -X github.com/bdwyertech/gontlm-proxy/cmd.ReleaseDate={{.Date}}

  - <<: *build
    id: darwin
    goos:
      - darwin
    env:
      - CGO_ENABLED=1 # CGO Required for proper DNS resolution

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ONLY_BINARY*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

release:
  # disable: true

signs:
  # - artifacts: checksum
  # - artifacts: all
